# Automatically generated by: ros2nix
{ lib, buildRosPackage, carla-msgs, carla-waypoint-types, rclpy, ros-compatibility }:
buildRosPackage rec {
  pname = "ros-rolling-carla-ad-agent";
  version = "0.0.1";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ carla-msgs carla-waypoint-types rclpy ros-compatibility ];

  meta = {
    description = "The carla_ad_agent package";
    license = with lib.licenses; [ mit ];
  };
}
