# Automatically generated by: ros2nix
{ lib, buildRosPackage }:
buildRosPackage rec {
  pname = "ros-rolling-carla-common";
  version = "0.0.1";

  src = ./.;

  buildType = "ament_python";

  meta = {
    description = "The carla_common package";
    license = with lib.licenses; [ mit ];
  };
}
