# Automatically generated by: ros2nix
{
  nix-ros-overlay ? builtins.fetchTarball "https://github.com/lopsided98/nix-ros-overlay/archive/master.tar.gz",
  pkgs ? import nix-ros-overlay { },
  rosDistro ? "rolling",
  extraPkgs ? { },
  extraPaths ? [ ],
  withPackages ? _: [ ],
  extraShellHook ? "",
}:
pkgs.mkShell {
  name = "ros2nix ${rosDistro} shell";
  packages = [
    (pkgs.rosPackages.${rosDistro}.buildEnv {
      wrapPrograms = false;
      paths =
        [
          pkgs.colcon
          pkgs.python312Packages.transforms3d
          pkgs.rosPackages.${rosDistro}.ros-core

          # Work around https://github.com/lopsided98/nix-ros-overlay/pull/624
          pkgs.rosPackages.${rosDistro}.ament-cmake-core
          pkgs.rosPackages.${rosDistro}.python-cmake-module
        ]
        ++ (
          with pkgs;
          with pkgs.rosPackages.${rosDistro};
          with extraPkgs;
          [
            # Dependencies from package.xml files
            ackermann-msgs
            ament-cmake
            ament-index-python
            ament-lint-auto
            ament-lint-common
            builtin-interfaces
            cv-bridge
            derived-object-msgs
            diagnostic-msgs
            geometry-msgs
            nav-msgs
            pcl-conversions
            python-qt-binding
            # python-transforms3d-pip
            qt5.qtbase
            rclcpp
            rclpy
            ros-environment
            rosgraph-msgs
            rosidl-default-generators
            rosidl-default-runtime
            rqt-gui-py
            rviz-common
            rviz2
            sensor-msgs
            shape-msgs
            std-msgs
            tf2-msgs
            tf2-ros
            visualization-msgs
          ]
        )
        ++ builtins.attrValues extraPkgs
        ++ extraPaths
        ++ withPackages (pkgs // pkgs.rosPackages.${rosDistro});
      }
    )
  ];
  shellHook = ''
    # Setup ROS 2 shell completion. Doing it in direnv is useless.
    if [[ ! $DIRENV_IN_ENVRC ]]; then
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete ros2)"
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete colcon)"
    fi
  '' + extraShellHook;
}
