# Automatically generated by: ros2nix
{ lib, buildRosPackage, ament-index-python, python-qt-binding, rqt-gui-py }:
buildRosPackage rec {
  pname = "ros-rolling-rqt-carla-control";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ ament-index-python python-qt-binding rqt-gui-py ];

  meta = {
    description = "The rqt_carla_control package";
    license = with lib.licenses; [ mit ];
  };
}
