# Automatically generated by: ros2nix --flake
{ lib, buildRosPackage, carla-common, carla-msgs, carla-ros-scenario-runner-types, rclpy, std-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-carla-ros-scenario-runner";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ carla-common carla-msgs carla-ros-scenario-runner-types rclpy std-msgs ];

  meta = {
    description = "The carla_ros_scenario_runner package";
    license = with lib.licenses; [ mit ];
  };
}
