# Automatically generated by: ros2nix
{ lib, buildRosPackage, carla-waypoint-types, nav-msgs, rclpy, ros-compatibility }:
buildRosPackage rec {
  pname = "ros-rolling-carla-waypoint-publisher";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ carla-waypoint-types nav-msgs rclpy ros-compatibility ];

  meta = {
    description = "The carla_waypoint_publisher package";
    license = with lib.licenses; [ mit ];
  };
}
