# Automatically generated by: ros2nix
{ lib, buildRosPackage, carla-msgs, rclpy, ros-compatibility }:
buildRosPackage rec {
  pname = "ros-rolling-carla-spawn-objects";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ carla-msgs rclpy ros-compatibility ];

  meta = {
    description = "The carla_spawn_objects package";
    license = with lib.licenses; [ mit ];
  };
}
