# Automatically generated by: ros2nix --flake
{ lib, buildRosPackage, ament-cmake, carla-ros-bridge, pcl-conversions, rclcpp, ros-core, sensor-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-pcl-recorder";
  version = "0.0.0";
  CMAKE_MODULE_PATH = "$CMAKE_MODULE_PATH;${pcl-conversions.out}/include/pcl_conversions";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ros-core rclcpp ];
  propagatedBuildInputs = [ carla-ros-bridge pcl-conversions ros-core rclcpp sensor-msgs ];
  nativeBuildInputs = [ ament-cmake ros-core rclcpp ];

  meta = {
    description = "The pcl_recorder package";
    license = with lib.licenses; [ mit ];
  };
}
