# Automatically generated by: ros2nix
{ lib, buildRosPackage, ament-cmake, carla-ros-bridge, pcl-conversions, rclcpp, sensor-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-pcl-recorder";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ carla-ros-bridge pcl-conversions rclcpp sensor-msgs ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "The pcl_recorder package";
    license = with lib.licenses; [ mit ];
  };
}
