# Automatically generated by: ros2nix
{ lib, buildRosPackage, carla-msgs, nav-msgs, rclpy }:
buildRosPackage rec {
  pname = "ros-rolling-carla-walker-agent";
  version = "0.0.1";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ carla-msgs nav-msgs rclpy ];

  meta = {
    description = "The carla_walker_agent package";
    license = with lib.licenses; [ mit ];
  };
}
