# Automatically generated by: ros2nix
{ lib, buildRosPackage, carla-msgs, rclpy, ros-compatibility, sensor-msgs, std-msgs, tf2-ros }:
buildRosPackage rec {
  pname = "ros-rolling-carla-manual-control";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ carla-msgs rclpy ros-compatibility sensor-msgs std-msgs tf2-ros ];

  meta = {
    description = "The carla_manual_control package";
    license = with lib.licenses; [ mit ];
  };
}
