# Automatically generated by: ros2nix
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common, nav-msgs, ros-environment, rosidl-default-generators, rosidl-default-runtime }:
buildRosPackage rec {
  pname = "ros-rolling-carla-waypoint-types";
  version = "0.1.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ros-environment rosidl-default-generators ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ nav-msgs rosidl-default-runtime ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "The carla_waypoint_types package";
    license = with lib.licenses; [ mit ];
  };
}
