# Automatically generated by: ros2nix
{ lib, buildRosPackage, ament-cmake, carla-msgs, carla-ros-scenario-runner-types, geometry-msgs, nav-msgs, qt5, rclcpp, rviz-common }:
buildRosPackage rec {
  pname = "ros-rolling-rviz-carla-plugin";
  version = "0.0.1";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ carla-msgs carla-ros-scenario-runner-types geometry-msgs nav-msgs qt5.qtbase rclcpp rviz-common ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "The carla_ros_bridge package";
    license = with lib.licenses; [ mit ];
  };
}
