# Automatically generated by: ros2nix
{ lib, buildRosPackage, ackermann-msgs, carla-ackermann-msgs, carla-msgs, carla-ros-bridge, rclpy, ros-compatibility, std-msgs, tf2-ros }:
buildRosPackage rec {
  pname = "ros-rolling-carla-ackermann-control";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ ackermann-msgs carla-ackermann-msgs carla-msgs carla-ros-bridge rclpy ros-compatibility std-msgs tf2-ros ];

  meta = {
    description = "The carla_ackermann_control package";
    license = with lib.licenses; [ mit ];
  };
}
