# Automatically generated by: ros2nix
{ lib, buildRosPackage, carla-common, carla-manual-control, carla-msgs, carla-spawn-objects, cv-bridge, derived-object-msgs, geometry-msgs, nav-msgs, python-transforms3d-pip, rclpy, ros-compatibility, rosgraph-msgs, rviz2, sensor-msgs, shape-msgs, std-msgs, tf2-msgs, tf2-ros, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-carla-ros-bridge";
  version = "0.0.1";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ carla-common carla-manual-control carla-msgs carla-spawn-objects cv-bridge derived-object-msgs geometry-msgs nav-msgs python-transforms3d-pip rclpy ros-compatibility rosgraph-msgs rviz2 sensor-msgs shape-msgs std-msgs tf2-msgs tf2-ros visualization-msgs ];

  meta = {
    description = "The carla_ros_bridge package";
    license = with lib.licenses; [ mit ];
  };
}
