# Automatically generated by: ros2nix --flake
{ lib, buildRosPackage, rclpy }:
buildRosPackage rec {
  pname = "ros-rolling-ros-compatibility";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ rclpy ];

  meta = {
    description = "The ros_compatibility package";
    license = with lib.licenses; [ mit ];
  };
}
