# Automatically generated by: ros2nix
{ lib, buildRosPackage, ament-cmake, carla-ad-agent, carla-manual-control, carla-ros-bridge, carla-ros-scenario-runner, carla-spawn-objects, carla-twist-to-control, carla-waypoint-publisher, rviz-carla-plugin, rviz2 }:
buildRosPackage rec {
  pname = "ros-rolling-carla-ad-demo";
  version = "0.0.1";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ carla-ad-agent carla-manual-control carla-ros-bridge carla-ros-scenario-runner carla-spawn-objects carla-twist-to-control carla-waypoint-publisher rviz-carla-plugin rviz2 ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "The carla_ad_demo package";
    license = with lib.licenses; [ mit ];
  };
}
