# Automatically generated by: ros2nix --flake
{ lib, buildRosPackage, rclpy }:
buildRosPackage rec {
  pname = "ros-rolling-carla-twist-to-control";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  propagatedBuildInputs = [ rclpy ];

  meta = {
    description = "The carla_twist_to_control package";
    license = with lib.licenses; [ mit ];
  };
}
